image: lasote/conanclang60

build:
  stage: build
  tags:
  - docker
  script:
  - conan create . sdl2/2.0.8@dandielo/stable
  - conan user $CONAN_USER -r $CONAN_SERVER -p $CONAN_PASSWORD
  - conan upload -r $CONAN_SERVER sdl2/2.0.8@dandielo/stable --all
