image: lasote/conanclang60

build:
  stage: build
  tags:
  - docker
  script:
  - conan create . SDL2/2.0.9@iceshard/stable
  - conan user $CONAN_USER -r $CONAN_SERVER -p $CONAN_PASSWORD
  - conan upload -r $CONAN_SERVER SDL2/2.0.9@iceshard/stable --all
